### ISSUE TITLE
Hello, is it okay to use B660M AORUS PRO DDR4 motherboard? The CPU is of the same model

### ISSUE THREAD

**Issue by cutestAlpaca** [dclive/Gigabyte_B660M-Elite-AX#2]
https://www.gigabyte.cn/Motherboard/B660M-AORUS-PRO-DDR4-rev-10#kf

**Comment by dclive** [comment]
I don't have one, so I can't test it.  If you have one and can test it, please let us know the results.   Both look very similar, but Elite has Wifi and 2 less USB3 ports.  You might need to remap USB, and I would remove the wifi kexts, but otherwise I suspect you'll be OK.
